package org.jxnu.pojo;

public class OptionInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column option_info.id
     *
     * @mbggenerated Sun Nov 25 16:35:55 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column option_info.question_id
     *
     * @mbggenerated Sun Nov 25 16:35:55 CST 2018
     */
    private Long questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column option_info.option_name
     *
     * @mbggenerated Sun Nov 25 16:35:55 CST 2018
     */
    private String optionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column option_info.details
     *
     * @mbggenerated Sun Nov 25 16:35:55 CST 2018
     */
    private String details;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column option_info.id
     *
     * @return the value of option_info.id
     *
     * @mbggenerated Sun Nov 25 16:35:55 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column option_info.id
     *
     * @param id the value for option_info.id
     *
     * @mbggenerated Sun Nov 25 16:35:55 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column option_info.question_id
     *
     * @return the value of option_info.question_id
     *
     * @mbggenerated Sun Nov 25 16:35:55 CST 2018
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column option_info.question_id
     *
     * @param questionId the value for option_info.question_id
     *
     * @mbggenerated Sun Nov 25 16:35:55 CST 2018
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column option_info.option_name
     *
     * @return the value of option_info.option_name
     *
     * @mbggenerated Sun Nov 25 16:35:55 CST 2018
     */
    public String getOptionName() {
        return optionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column option_info.option_name
     *
     * @param optionName the value for option_info.option_name
     *
     * @mbggenerated Sun Nov 25 16:35:55 CST 2018
     */
    public void setOptionName(String optionName) {
        this.optionName = optionName == null ? null : optionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column option_info.details
     *
     * @return the value of option_info.details
     *
     * @mbggenerated Sun Nov 25 16:35:55 CST 2018
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column option_info.details
     *
     * @param details the value for option_info.details
     *
     * @mbggenerated Sun Nov 25 16:35:55 CST 2018
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }
}