package org.jxnu.pojo;

import java.util.Date;

public class PaperInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_info.id
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_info.paper_name
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    private String paperName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_info.paper_date
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    private Date paperDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_info.teacher_id
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    private String teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_info.duration
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    private Integer duration;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_info.id
     *
     * @return the value of paper_info.id
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_info.id
     *
     * @param id the value for paper_info.id
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_info.paper_name
     *
     * @return the value of paper_info.paper_name
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    public String getPaperName() {
        return paperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_info.paper_name
     *
     * @param paperName the value for paper_info.paper_name
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    public void setPaperName(String paperName) {
        this.paperName = paperName == null ? null : paperName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_info.paper_date
     *
     * @return the value of paper_info.paper_date
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    public Date getPaperDate() {
        return paperDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_info.paper_date
     *
     * @param paperDate the value for paper_info.paper_date
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    public void setPaperDate(Date paperDate) {
        this.paperDate = paperDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_info.teacher_id
     *
     * @return the value of paper_info.teacher_id
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_info.teacher_id
     *
     * @param teacherId the value for paper_info.teacher_id
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId == null ? null : teacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_info.duration
     *
     * @return the value of paper_info.duration
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_info.duration
     *
     * @param duration the value for paper_info.duration
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }
}