package org.jxnu.pojo;

public class PaperQuestion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_question.id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_question.paper_id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    private Long paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_question.question_id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    private Long questionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_question.id
     *
     * @return the value of paper_question.id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_question.id
     *
     * @param id the value for paper_question.id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_question.paper_id
     *
     * @return the value of paper_question.paper_id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public Long getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_question.paper_id
     *
     * @param paperId the value for paper_question.paper_id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public void setPaperId(Long paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_question.question_id
     *
     * @return the value of paper_question.question_id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_question.question_id
     *
     * @param questionId the value for paper_question.question_id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }
}