package org.jxnu.pojo;

public class PassageQuestion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passage_question.id
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passage_question.passage_id
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    private Long passageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passage_question.question_id
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    private Long questionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passage_question.id
     *
     * @return the value of passage_question.id
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passage_question.id
     *
     * @param id the value for passage_question.id
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passage_question.passage_id
     *
     * @return the value of passage_question.passage_id
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    public Long getPassageId() {
        return passageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passage_question.passage_id
     *
     * @param passageId the value for passage_question.passage_id
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    public void setPassageId(Long passageId) {
        this.passageId = passageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passage_question.question_id
     *
     * @return the value of passage_question.question_id
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passage_question.question_id
     *
     * @param questionId the value for passage_question.question_id
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }
}