package org.jxnu.pojo;

public class StudentAnswerEssay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_answer_essay.id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_answer_essay.student_answer_id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    private Long studentAnswerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_answer_essay.essay
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    private String essay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_answer_essay.id
     *
     * @return the value of student_answer_essay.id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_answer_essay.id
     *
     * @param id the value for student_answer_essay.id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_answer_essay.student_answer_id
     *
     * @return the value of student_answer_essay.student_answer_id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public Long getStudentAnswerId() {
        return studentAnswerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_answer_essay.student_answer_id
     *
     * @param studentAnswerId the value for student_answer_essay.student_answer_id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public void setStudentAnswerId(Long studentAnswerId) {
        this.studentAnswerId = studentAnswerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_answer_essay.essay
     *
     * @return the value of student_answer_essay.essay
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public String getEssay() {
        return essay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_answer_essay.essay
     *
     * @param essay the value for student_answer_essay.essay
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public void setEssay(String essay) {
        this.essay = essay == null ? null : essay.trim();
    }
}