package org.jxnu.pojo;

import java.util.Date;

public class StudentPaper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_paper.id
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_paper.student_id
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_paper.paper_id
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    private Long paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_paper.start_time
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_paper.end_time
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_paper.score
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_paper.correct
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    private Integer correct;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_paper.id
     *
     * @return the value of student_paper.id
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_paper.id
     *
     * @param id the value for student_paper.id
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_paper.student_id
     *
     * @return the value of student_paper.student_id
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_paper.student_id
     *
     * @param studentId the value for student_paper.student_id
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_paper.paper_id
     *
     * @return the value of student_paper.paper_id
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    public Long getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_paper.paper_id
     *
     * @param paperId the value for student_paper.paper_id
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    public void setPaperId(Long paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_paper.start_time
     *
     * @return the value of student_paper.start_time
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_paper.start_time
     *
     * @param startTime the value for student_paper.start_time
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_paper.end_time
     *
     * @return the value of student_paper.end_time
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_paper.end_time
     *
     * @param endTime the value for student_paper.end_time
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_paper.score
     *
     * @return the value of student_paper.score
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_paper.score
     *
     * @param score the value for student_paper.score
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_paper.correct
     *
     * @return the value of student_paper.correct
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    public Integer getCorrect() {
        return correct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_paper.correct
     *
     * @param correct the value for student_paper.correct
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    public void setCorrect(Integer correct) {
        this.correct = correct;
    }
}