package org.jxnu.pojo;

import java.util.Date;

public class Video {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.user_id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.name
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.url
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.descprit
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    private String descprit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.upload_date
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    private Date uploadDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.id
     *
     * @return the value of video.id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.id
     *
     * @param id the value for video.id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.user_id
     *
     * @return the value of video.user_id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.user_id
     *
     * @param userId the value for video.user_id
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.name
     *
     * @return the value of video.name
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.name
     *
     * @param name the value for video.name
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.url
     *
     * @return the value of video.url
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.url
     *
     * @param url the value for video.url
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.descprit
     *
     * @return the value of video.descprit
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public String getDescprit() {
        return descprit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.descprit
     *
     * @param descprit the value for video.descprit
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public void setDescprit(String descprit) {
        this.descprit = descprit == null ? null : descprit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.upload_date
     *
     * @return the value of video.upload_date
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public Date getUploadDate() {
        return uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.upload_date
     *
     * @param uploadDate the value for video.upload_date
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }
}