package org.jxnu.dao.generator;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jxnu.pojo.OptionInfo;
import org.jxnu.pojo.OptionInfoExample;

public interface OptionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int countByExample(OptionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int deleteByExample(OptionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int insert(OptionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int insertSelective(OptionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    List<OptionInfo> selectByExample(OptionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    OptionInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") OptionInfo record, @Param("example") OptionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int updateByExample(@Param("record") OptionInfo record, @Param("example") OptionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int updateByPrimaryKeySelective(OptionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table option_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int updateByPrimaryKey(OptionInfo record);
}