package org.jxnu.dao.generator;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jxnu.pojo.PaperInfo;
import org.jxnu.pojo.PaperInfoExample;

public interface PaperInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    int countByExample(PaperInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    int deleteByExample(PaperInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    int insert(PaperInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    int insertSelective(PaperInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    List<PaperInfo> selectByExample(PaperInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    PaperInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    int updateByExampleSelective(@Param("record") PaperInfo record, @Param("example") PaperInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    int updateByExample(@Param("record") PaperInfo record, @Param("example") PaperInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    int updateByPrimaryKeySelective(PaperInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbggenerated Wed Nov 28 11:14:02 CST 2018
     */
    int updateByPrimaryKey(PaperInfo record);
    
    List<PaperInfo> selectAll();
}