package org.jxnu.dao.generator;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jxnu.pojo.PassageInfo;
import org.jxnu.pojo.PassageInfoExample;

public interface PassageInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int countByExample(PassageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int deleteByExample(PassageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int insert(PassageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int insertSelective(PassageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    List<PassageInfo> selectByExampleWithBLOBs(PassageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    List<PassageInfo> selectByExample(PassageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    PassageInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") PassageInfo record, @Param("example") PassageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") PassageInfo record, @Param("example") PassageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int updateByExample(@Param("record") PassageInfo record, @Param("example") PassageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int updateByPrimaryKeySelective(PassageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(PassageInfo record);
}