package org.jxnu.dao.generator;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jxnu.pojo.PassageQuestion;
import org.jxnu.pojo.PassageQuestionExample;

public interface PassageQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_question
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    int countByExample(PassageQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_question
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    int deleteByExample(PassageQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_question
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_question
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    int insert(PassageQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_question
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    int insertSelective(PassageQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_question
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    List<PassageQuestion> selectByExample(PassageQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_question
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    PassageQuestion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_question
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") PassageQuestion record, @Param("example") PassageQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_question
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    int updateByExample(@Param("record") PassageQuestion record, @Param("example") PassageQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_question
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    int updateByPrimaryKeySelective(PassageQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passage_question
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    int updateByPrimaryKey(PassageQuestion record);
}