package org.jxnu.dao.generator;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jxnu.pojo.QuestionInfo;
import org.jxnu.pojo.QuestionInfoExample;

public interface QuestionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int countByExample(QuestionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int deleteByExample(QuestionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int insert(QuestionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int insertSelective(QuestionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    List<QuestionInfo> selectByExample(QuestionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    QuestionInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") QuestionInfo record, @Param("example") QuestionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int updateByExample(@Param("record") QuestionInfo record, @Param("example") QuestionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int updateByPrimaryKeySelective(QuestionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_info
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int updateByPrimaryKey(QuestionInfo record);
}