package org.jxnu.dao.generator;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jxnu.pojo.StudentPaperAnswer;
import org.jxnu.pojo.StudentPaperAnswerExample;

public interface StudentPaperAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper_answer
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int countByExample(StudentPaperAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper_answer
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int deleteByExample(StudentPaperAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper_answer
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper_answer
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int insert(StudentPaperAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper_answer
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int insertSelective(StudentPaperAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper_answer
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    List<StudentPaperAnswer> selectByExample(StudentPaperAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper_answer
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    StudentPaperAnswer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper_answer
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") StudentPaperAnswer record, @Param("example") StudentPaperAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper_answer
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int updateByExample(@Param("record") StudentPaperAnswer record, @Param("example") StudentPaperAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper_answer
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int updateByPrimaryKeySelective(StudentPaperAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper_answer
     *
     * @mbggenerated Tue Dec 04 15:05:36 CST 2018
     */
    int updateByPrimaryKey(StudentPaperAnswer record);
}