package org.jxnu.dao.generator;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jxnu.pojo.StudentPaper;
import org.jxnu.pojo.StudentPaperExample;

public interface StudentPaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    int countByExample(StudentPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    int deleteByExample(StudentPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    int insert(StudentPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    int insertSelective(StudentPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    List<StudentPaper> selectByExample(StudentPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    StudentPaper selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") StudentPaper record, @Param("example") StudentPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    int updateByExample(@Param("record") StudentPaper record, @Param("example") StudentPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    int updateByPrimaryKeySelective(StudentPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_paper
     *
     * @mbggenerated Wed Dec 05 10:01:31 CST 2018
     */
    int updateByPrimaryKey(StudentPaper record);
}