package org.jxnu.dao.generator;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jxnu.pojo.StudentAnswerEssay;
import org.jxnu.pojo.StudentAnswerEssayExample;

public interface StudentAnswerEssayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_answer_essay
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    int countByExample(StudentAnswerEssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_answer_essay
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    int deleteByExample(StudentAnswerEssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_answer_essay
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_answer_essay
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    int insert(StudentAnswerEssay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_answer_essay
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    int insertSelective(StudentAnswerEssay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_answer_essay
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    List<StudentAnswerEssay> selectByExampleWithBLOBs(StudentAnswerEssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_answer_essay
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    List<StudentAnswerEssay> selectByExample(StudentAnswerEssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_answer_essay
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    StudentAnswerEssay selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_answer_essay
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") StudentAnswerEssay record, @Param("example") StudentAnswerEssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_answer_essay
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") StudentAnswerEssay record, @Param("example") StudentAnswerEssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_answer_essay
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    int updateByExample(@Param("record") StudentAnswerEssay record, @Param("example") StudentAnswerEssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_answer_essay
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    int updateByPrimaryKeySelective(StudentAnswerEssay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_answer_essay
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(StudentAnswerEssay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_answer_essay
     *
     * @mbggenerated Sun Nov 25 16:35:56 CST 2018
     */
    int updateByPrimaryKey(StudentAnswerEssay record);
}